"use client";

import {
  CheckIcon as hugeicons_CheckIcon,
  XIcon as hugeicons_XIcon,
  ChevronDownIcon as hugeicons_ChevronDownIcon,
  ChevronLeftIcon as hugeicons_ChevronLeftIcon,
  ChevronRightIcon as hugeicons_ChevronRightIcon,
  ChevronUpIcon as hugeicons_ChevronUpIcon,
  SearchIcon as hugeicons_SearchIcon,
  LoaderCircleIcon as hugeicons_LoaderCircleIcon,
  GripVerticalIcon as hugeicons_GripVerticalIcon,
  BoldIcon as hugeicons_BoldIcon,
  ItalicIcon as hugeicons_ItalicIcon,
  UnderlineIcon as hugeicons_UnderlineIcon,
  ArrowUpIcon as hugeicons_ArrowUpIcon,
  PlusIcon as hugeicons_PlusIcon,
  VideoIcon as hugeicons_VideoIcon,
  CheckCheckIcon as hugeicons_CheckCheckIcon,
  SendIcon as hugeicons_SendIcon,
  MicIcon as hugeicons_MicIcon,
  SmileIcon as hugeicons_SmileIcon,
  PaperclipIcon as hugeicons_PaperclipIcon,
  PhoneIcon as hugeicons_PhoneIcon,
  EllipsisVerticalIcon as hugeicons_EllipsisVerticalIcon,
  SettingsIcon as hugeicons_SettingsIcon,
  UserIcon as hugeicons_UserIcon,
  FileIcon as hugeicons_FileIcon,
  CircleCheckIcon as hugeicons_CircleCheckIcon,
  OctagonXIcon as hugeicons_OctagonXIcon,
  InfoIcon as hugeicons_InfoIcon,
  MailIcon as hugeicons_MailIcon,
  CircleIcon as hugeicons_CircleIcon,
  ArrowLeftIcon as hugeicons_ArrowLeftIcon,
  ArrowRightIcon as hugeicons_ArrowRightIcon,
  ChevronsUpDown as hugeicons_ChevronsUpDown,
} from "@hugeicons/core-free-icons";
import { HugeiconsIcon } from "@hugeicons/react";
import {
  CheckIcon as phosphor_CheckIcon,
  XIcon as phosphor_XIcon,
  CaretDownIcon as phosphor_CaretDownIcon,
  CaretLeftIcon as phosphor_CaretLeftIcon,
  CaretRightIcon as phosphor_CaretRightIcon,
  CaretUpIcon as phosphor_CaretUpIcon,
  CaretUpDownIcon as phosphor_CaretUpDownIcon,
  MagnifyingGlassIcon as phosphor_MagnifyingGlassIcon,
  CircleNotchIcon as phosphor_CircleNotchIcon,
  DotsSixVerticalIcon as phosphor_DotsSixVerticalIcon,
  TextBIcon as phosphor_TextBIcon,
  TextItalicIcon as phosphor_TextItalicIcon,
  TextUnderlineIcon as phosphor_TextUnderlineIcon,
  ArrowUpIcon as phosphor_ArrowUpIcon,
  PlusIcon as phosphor_PlusIcon,
  VideoCameraIcon as phosphor_VideoCameraIcon,
  ChecksIcon as phosphor_ChecksIcon,
  PaperPlaneTiltIcon as phosphor_PaperPlaneTiltIcon,
  MicrophoneIcon as phosphor_MicrophoneIcon,
  SmileyIcon as phosphor_SmileyIcon,
  PaperclipIcon as phosphor_PaperclipIcon,
  PhoneIcon as phosphor_PhoneIcon,
  DotsThreeVerticalIcon as phosphor_DotsThreeVerticalIcon,
  GearIcon as phosphor_GearIcon,
  UserIcon as phosphor_UserIcon,
  FileIcon as phosphor_FileIcon,
  CheckCircleIcon as phosphor_CheckCircleIcon,
  InfoIcon as phosphor_InfoIcon,
  EnvelopeIcon as phosphor_EnvelopeIcon,
  CircleIcon as phosphor_CircleIcon,
  ArrowLeftIcon as phosphor_ArrowLeftIcon,
  ArrowRightIcon as phosphor_ArrowRightIcon,
  WarningOctagonIcon as phosphor_WarningOctagonIcon,
} from "@phosphor-icons/react";
import {
  RiCheckLine as remixicon_RiCheckLine,
  RiCloseLine as remixicon_RiCloseLine,
  RiArrowDownSLine as remixicon_RiArrowDownSLine,
  RiArrowLeftSLine as remixicon_RiArrowLeftSLine,
  RiArrowRightSLine as remixicon_RiArrowRightSLine,
  RiArrowUpSLine as remixicon_RiArrowUpSLine,
  RiExpandUpDownLine as remixicon_RiExpandUpDownLine,
  RiSearchLine as remixicon_RiSearchLine,
  RiLoader4Line as remixicon_RiLoader4Line,
  RiDraggable as remixicon_RiDraggable,
  RiBold as remixicon_RiBold,
  RiItalic as remixicon_RiItalic,
  RiUnderline as remixicon_RiUnderline,
  RiArrowUpLine as remixicon_RiArrowUpLine,
  RiVideoOnLine as remixicon_RiVideoOnLine,
  RiCheckDoubleLine as remixicon_RiCheckDoubleLine,
  RiSendPlaneLine as remixicon_RiSendPlaneLine,
  RiMicLine as remixicon_RiMicLine,
  RiEmotionHappyLine as remixicon_RiEmotionHappyLine,
  RiAttachmentLine as remixicon_RiAttachmentLine,
  RiPhoneLine as remixicon_RiPhoneLine,
  RiMore2Line as remixicon_RiMore2Line,
  RiSettings3Line as remixicon_RiSettings3Line,
  RiUserLine as remixicon_RiUserLine,
  RiFileLine as remixicon_RiFileLine,
  RiCheckboxCircleLine as remixicon_RiCheckboxCircleLine,
  RiCloseCircleLine as remixicon_RiCloseCircleLine,
  RiMailLine as remixicon_RiMailLine,
  RiCheckboxBlankCircleLine as remixicon_RiCheckboxBlankCircleLine,
  RiArrowLeftLine as remixicon_RiArrowLeftLine,
  RiArrowRightLine as remixicon_RiArrowRightLine,
  RiAddLine as remixicon_RiAddLine,
  RiInformationLine as remixicon_RiInformationLine,
} from "@remixicon/react";
import {
  IconCheck as tabler_IconCheck,
  IconX as tabler_IconX,
  IconChevronDown as tabler_IconChevronDown,
  IconChevronLeft as tabler_IconChevronLeft,
  IconChevronRight as tabler_IconChevronRight,
  IconChevronUp as tabler_IconChevronUp,
  IconSelector as tabler_IconSelector,
  IconSearch as tabler_IconSearch,
  IconLoader2 as tabler_IconLoader2,
  IconGripVertical as tabler_IconGripVertical,
  IconBold as tabler_IconBold,
  IconItalic as tabler_IconItalic,
  IconUnderline as tabler_IconUnderline,
  IconArrowUp as tabler_IconArrowUp,
  IconPlus as tabler_IconPlus,
  IconVideo as tabler_IconVideo,
  IconSend as tabler_IconSend,
  IconPaperclip as tabler_IconPaperclip,
  IconPhone as tabler_IconPhone,
  IconDotsVertical as tabler_IconDotsVertical,
  IconSettings as tabler_IconSettings,
  IconUser as tabler_IconUser,
  IconFile as tabler_IconFile,
  IconCircleCheck as tabler_IconCircleCheck,
  IconAlertOctagon as tabler_IconAlertOctagon,
  IconMail as tabler_IconMail,
  IconCircle as tabler_IconCircle,
  IconArrowLeft as tabler_IconArrowLeft,
  IconArrowRight as tabler_IconArrowRight,
  IconChecks as tabler_IconChecks,
  IconMicrophone as tabler_IconMicrophone,
  IconMoodSmile as tabler_IconMoodSmile,
  IconInfoCircle as tabler_IconInfoCircle,
} from "@tabler/icons-react";
import {
  Check as lucide_Check,
  X as lucide_X,
  ChevronDown as lucide_ChevronDown,
  ChevronLeft as lucide_ChevronLeft,
  ChevronRight as lucide_ChevronRight,
  ChevronUp as lucide_ChevronUp,
  ChevronsUpDown as lucide_ChevronsUpDown,
  Search as lucide_Search,
  LoaderCircle as lucide_LoaderCircle,
  GripVertical as lucide_GripVertical,
  Bold as lucide_Bold,
  Italic as lucide_Italic,
  Underline as lucide_Underline,
  ArrowUp as lucide_ArrowUp,
  Plus as lucide_Plus,
  Video as lucide_Video,
  CheckCheck as lucide_CheckCheck,
  Send as lucide_Send,
  Mic as lucide_Mic,
  Smile as lucide_Smile,
  Paperclip as lucide_Paperclip,
  Phone as lucide_Phone,
  EllipsisVertical as lucide_EllipsisVertical,
  Settings as lucide_Settings,
  User as lucide_User,
  File as lucide_File,
  CircleCheck as lucide_CircleCheck,
  OctagonX as lucide_OctagonX,
  Info as lucide_Info,
  Mail as lucide_Mail,
  Circle as lucide_Circle,
  ArrowLeft as lucide_ArrowLeft,
  ArrowRight as lucide_ArrowRight,
} from "lucide-react";
import { createContext, createElement, useContext } from "react";
import type { CSSProperties, ReactNode } from "react";

export const ICON_LIBRARIES = [
  "lucide",
  "tabler",
  "hugeicons",
  "phosphor",
  "remixicon",
] as const;
export type IconLibrary = (typeof ICON_LIBRARIES)[number];
const IconContext = createContext<IconLibrary>("lucide");
export const FramecnIconProvider = ({
  library,
  children,
}: {
  library: IconLibrary;
  children?: ReactNode;
}) => createElement(IconContext.Provider, { value: library }, children);

const icons = {
  hugeicons: {
    ArrowLeft: hugeicons_ArrowLeftIcon,
    ArrowRight: hugeicons_ArrowRightIcon,
    ArrowUp: hugeicons_ArrowUpIcon,
    Bold: hugeicons_BoldIcon,
    Check: hugeicons_CheckIcon,
    CheckCheck: hugeicons_CheckCheckIcon,
    ChevronDown: hugeicons_ChevronDownIcon,
    ChevronLeft: hugeicons_ChevronLeftIcon,
    ChevronRight: hugeicons_ChevronRightIcon,
    ChevronUp: hugeicons_ChevronUpIcon,
    ChevronsUpDown: hugeicons_ChevronsUpDown,
    Circle: hugeicons_CircleIcon,
    CircleCheck: hugeicons_CircleCheckIcon,
    EllipsisVertical: hugeicons_EllipsisVerticalIcon,
    File: hugeicons_FileIcon,
    GripVertical: hugeicons_GripVerticalIcon,
    Info: hugeicons_InfoIcon,
    Italic: hugeicons_ItalicIcon,
    LoaderCircle: hugeicons_LoaderCircleIcon,
    Mail: hugeicons_MailIcon,
    Mic: hugeicons_MicIcon,
    OctagonX: hugeicons_OctagonXIcon,
    Paperclip: hugeicons_PaperclipIcon,
    Phone: hugeicons_PhoneIcon,
    Plus: hugeicons_PlusIcon,
    Search: hugeicons_SearchIcon,
    Send: hugeicons_SendIcon,
    Settings: hugeicons_SettingsIcon,
    Smile: hugeicons_SmileIcon,
    Underline: hugeicons_UnderlineIcon,
    User: hugeicons_UserIcon,
    Video: hugeicons_VideoIcon,
    X: hugeicons_XIcon,
  },
  lucide: {
    ArrowLeft: lucide_ArrowLeft,
    ArrowRight: lucide_ArrowRight,
    ArrowUp: lucide_ArrowUp,
    Bold: lucide_Bold,
    Check: lucide_Check,
    CheckCheck: lucide_CheckCheck,
    ChevronDown: lucide_ChevronDown,
    ChevronLeft: lucide_ChevronLeft,
    ChevronRight: lucide_ChevronRight,
    ChevronUp: lucide_ChevronUp,
    ChevronsUpDown: lucide_ChevronsUpDown,
    Circle: lucide_Circle,
    CircleCheck: lucide_CircleCheck,
    EllipsisVertical: lucide_EllipsisVertical,
    File: lucide_File,
    GripVertical: lucide_GripVertical,
    Info: lucide_Info,
    Italic: lucide_Italic,
    LoaderCircle: lucide_LoaderCircle,
    Mail: lucide_Mail,
    Mic: lucide_Mic,
    OctagonX: lucide_OctagonX,
    Paperclip: lucide_Paperclip,
    Phone: lucide_Phone,
    Plus: lucide_Plus,
    Search: lucide_Search,
    Send: lucide_Send,
    Settings: lucide_Settings,
    Smile: lucide_Smile,
    Underline: lucide_Underline,
    User: lucide_User,
    Video: lucide_Video,
    X: lucide_X,
  },
  phosphor: {
    ArrowLeft: phosphor_ArrowLeftIcon,
    ArrowRight: phosphor_ArrowRightIcon,
    ArrowUp: phosphor_ArrowUpIcon,
    Bold: phosphor_TextBIcon,
    Check: phosphor_CheckIcon,
    CheckCheck: phosphor_ChecksIcon,
    ChevronDown: phosphor_CaretDownIcon,
    ChevronLeft: phosphor_CaretLeftIcon,
    ChevronRight: phosphor_CaretRightIcon,
    ChevronUp: phosphor_CaretUpIcon,
    ChevronsUpDown: phosphor_CaretUpDownIcon,
    Circle: phosphor_CircleIcon,
    CircleCheck: phosphor_CheckCircleIcon,
    EllipsisVertical: phosphor_DotsThreeVerticalIcon,
    File: phosphor_FileIcon,
    GripVertical: phosphor_DotsSixVerticalIcon,
    Info: phosphor_InfoIcon,
    Italic: phosphor_TextItalicIcon,
    LoaderCircle: phosphor_CircleNotchIcon,
    Mail: phosphor_EnvelopeIcon,
    Mic: phosphor_MicrophoneIcon,
    OctagonX: phosphor_WarningOctagonIcon,
    Paperclip: phosphor_PaperclipIcon,
    Phone: phosphor_PhoneIcon,
    Plus: phosphor_PlusIcon,
    Search: phosphor_MagnifyingGlassIcon,
    Send: phosphor_PaperPlaneTiltIcon,
    Settings: phosphor_GearIcon,
    Smile: phosphor_SmileyIcon,
    Underline: phosphor_TextUnderlineIcon,
    User: phosphor_UserIcon,
    Video: phosphor_VideoCameraIcon,
    X: phosphor_XIcon,
  },
  remixicon: {
    ArrowLeft: remixicon_RiArrowLeftLine,
    ArrowRight: remixicon_RiArrowRightLine,
    ArrowUp: remixicon_RiArrowUpLine,
    Bold: remixicon_RiBold,
    Check: remixicon_RiCheckLine,
    CheckCheck: remixicon_RiCheckDoubleLine,
    ChevronDown: remixicon_RiArrowDownSLine,
    ChevronLeft: remixicon_RiArrowLeftSLine,
    ChevronRight: remixicon_RiArrowRightSLine,
    ChevronUp: remixicon_RiArrowUpSLine,
    ChevronsUpDown: remixicon_RiExpandUpDownLine,
    Circle: remixicon_RiCheckboxBlankCircleLine,
    CircleCheck: remixicon_RiCheckboxCircleLine,
    EllipsisVertical: remixicon_RiMore2Line,
    File: remixicon_RiFileLine,
    GripVertical: remixicon_RiDraggable,
    Info: remixicon_RiInformationLine,
    Italic: remixicon_RiItalic,
    LoaderCircle: remixicon_RiLoader4Line,
    Mail: remixicon_RiMailLine,
    Mic: remixicon_RiMicLine,
    OctagonX: remixicon_RiCloseCircleLine,
    Paperclip: remixicon_RiAttachmentLine,
    Phone: remixicon_RiPhoneLine,
    Plus: remixicon_RiAddLine,
    Search: remixicon_RiSearchLine,
    Send: remixicon_RiSendPlaneLine,
    Settings: remixicon_RiSettings3Line,
    Smile: remixicon_RiEmotionHappyLine,
    Underline: remixicon_RiUnderline,
    User: remixicon_RiUserLine,
    Video: remixicon_RiVideoOnLine,
    X: remixicon_RiCloseLine,
  },
  tabler: {
    ArrowLeft: tabler_IconArrowLeft,
    ArrowRight: tabler_IconArrowRight,
    ArrowUp: tabler_IconArrowUp,
    Bold: tabler_IconBold,
    Check: tabler_IconCheck,
    CheckCheck: tabler_IconChecks,
    ChevronDown: tabler_IconChevronDown,
    ChevronLeft: tabler_IconChevronLeft,
    ChevronRight: tabler_IconChevronRight,
    ChevronUp: tabler_IconChevronUp,
    ChevronsUpDown: tabler_IconSelector,
    Circle: tabler_IconCircle,
    CircleCheck: tabler_IconCircleCheck,
    EllipsisVertical: tabler_IconDotsVertical,
    File: tabler_IconFile,
    GripVertical: tabler_IconGripVertical,
    Info: tabler_IconInfoCircle,
    Italic: tabler_IconItalic,
    LoaderCircle: tabler_IconLoader2,
    Mail: tabler_IconMail,
    Mic: tabler_IconMicrophone,
    OctagonX: tabler_IconAlertOctagon,
    Paperclip: tabler_IconPaperclip,
    Phone: tabler_IconPhone,
    Plus: tabler_IconPlus,
    Search: tabler_IconSearch,
    Send: tabler_IconSend,
    Settings: tabler_IconSettings,
    Smile: tabler_IconMoodSmile,
    Underline: tabler_IconUnderline,
    User: tabler_IconUser,
    Video: tabler_IconVideo,
    X: tabler_IconX,
  },
} as const;
export type FramecnIconName = keyof typeof icons.lucide;
export interface FramecnIconProps {
  name: FramecnIconName;
  size?: number;
  color?: string;
  style?: CSSProperties;
  className?: string;
}
export const FramecnIcon = ({
  name,
  size = 16,
  color = "currentColor",
  style,
  className,
}: FramecnIconProps) => {
  const library = useContext(IconContext);
  const props = { "aria-hidden": true as const, className, color, size, style };
  if (library === "hugeicons") {
    return createElement(HugeiconsIcon, {
      ...props,
      icon: icons.hugeicons[name],
      strokeWidth: 2,
    });
  }
  const Icon = icons[library][name];
  return createElement(Icon, props);
};
