import type { ComponentConfig } from "@/lib/customizer-config";
import { FONT_WEIGHT_OPTIONS, FPS, H, W } from "@/lib/customizer-config";

export const nodeRevealConfig: ComponentConfig = {
  componentName: "NodeReveal",
  compositionHeight: H,
  compositionWidth: W,
  controls: {
    background: { default: "#4e4e50", label: "Background", type: "color" },
    color: { default: "#ffffff", label: "Text color", type: "color" },
    easing: {
      default: "expo",
      label: "Easing",
      options: ["quad", "cubic", "quart", "quint", "circ", "expo", "linear"],
      type: "select",
    },
    fit: {
      default: "cover",
      label: "Fit",
      options: ["cover", "contain", "fill"],
      type: "select",
    },
    fontSize: {
      default: 56,
      label: "Font size",
      max: 160,
      min: 16,
      step: 2,
      type: "number",
    },
    fontWeight: {
      default: "500",
      label: "Font weight",
      options: FONT_WEIGHT_OPTIONS,
      type: "select",
    },
    gapFrom: {
      default: 6,
      label: "Gap from",
      max: 60,
      min: 0,
      step: 1,
      type: "number",
    },
    gapTo: {
      default: 56,
      label: "Gap to",
      max: 200,
      min: 0,
      step: 2,
      type: "number",
    },
    handleSize: {
      default: 10,
      label: "Handle size",
      max: 28,
      min: 2,
      step: 1,
      type: "number",
    },
    handles: { default: true, label: "Corner handles", type: "boolean" },
    landAt: {
      default: 0.55,
      label: "Land at",
      max: 1,
      min: 0.2,
      step: 0.05,
      type: "number",
    },
    lead: { default: "SHADCN", label: "Lead text", type: "text" },
    nodeBackground: {
      default: "#000000",
      label: "Node background",
      type: "color",
    },
    openAt: {
      default: 0.12,
      label: "Open at",
      max: 0.6,
      min: 0,
      step: 0.02,
      type: "number",
    },
    radius: {
      default: 0,
      label: "Radius",
      max: 60,
      min: 0,
      step: 1,
      type: "number",
    },
    ratio: {
      default: "1:1",
      label: "Ratio",
      options: ["1:1", "4:3", "16:9", "3:4", "9:16"],
      type: "select",
    },
    size: {
      default: 440,
      label: "Size",
      max: 680,
      min: 80,
      step: 10,
      type: "number",
    },
    speed: {
      default: 1,
      label: "Speed",
      max: 3,
      min: 0.25,
      step: 0.25,
      type: "number",
    },
    src: {
      default:
        "https://raw.githubusercontent.com/shadcn-labs/framecn/main/.github/assets/gh.png",
      label: "Image URL",
      type: "text",
    },
    trail: { default: "LABS", label: "Trail text", type: "text" },
  },
  durationInFrames: 120,
  fps: FPS,
  importPath: "@/components/framecn/node-reveal",
};
