import type { ComponentConfig } from "@/lib/customizer-config";
import { FONT_WEIGHT_OPTIONS, FPS, H, W } from "@/lib/customizer-config";

export const formatMorphConfig: ComponentConfig = {
  componentName: "FormatMorph",
  compositionHeight: H,
  compositionWidth: W,
  controls: {
    background: { default: "#4e4e50", label: "Background", type: "color" },
    color: { default: "#ffffff", label: "Text color", type: "color" },
    easing: {
      default: "quint",
      label: "Easing",
      options: ["quad", "cubic", "quart", "quint", "circ", "expo", "linear"],
      type: "select",
    },
    fontSize: {
      default: 128,
      label: "Font size",
      max: 220,
      min: 48,
      step: 2,
      type: "number",
    },
    fontWeight: {
      default: "500",
      label: "Font weight",
      options: FONT_WEIGHT_OPTIONS,
      type: "select",
    },
    gap: {
      default: 20,
      label: "Gap",
      max: 80,
      min: 0,
      step: 2,
      type: "number",
    },
    holdRatio: {
      default: 0.45,
      label: "Hold",
      max: 0.8,
      min: 0.1,
      step: 0.05,
      type: "number",
    },
    lagMs: {
      default: 40,
      label: "Type lag (ms)",
      max: 200,
      min: 0,
      step: 10,
      type: "number",
    },
    lead: { default: "FRA", label: "Lead text", type: "text" },
    maxHeight: {
      default: 440,
      label: "Max height",
      max: 640,
      min: 120,
      step: 10,
      type: "number",
    },
    maxWidth: {
      default: 460,
      label: "Max width",
      max: 800,
      min: 120,
      step: 10,
      type: "number",
    },
    radiusRatio: {
      default: 0.08,
      label: "Radius ratio",
      max: 0.5,
      min: 0,
      step: 0.01,
      type: "number",
    },
    speed: {
      default: 1,
      label: "Speed",
      max: 3,
      min: 0.25,
      step: 0.25,
      type: "number",
    },
    src: {
      default:
        "https://raw.githubusercontent.com/shadcn-labs/framecn/main/.github/assets/gh.png",
      label: "Image URL",
      type: "text",
    },
    trail: { default: "MECN", label: "Trail text", type: "text" },
  },
  durationInFrames: 180,
  fps: FPS,
  importPath: "@/components/framecn/format-morph",
};
