import type { ControlConfig } from "@/lib/customizer-config";
import { ICON_LIBRARIES } from "@/registry/bases/editframe/lib/icons";
import {
  BASE_COLOR_NAMES,
  THEME_NAMES,
} from "@/registry/bases/editframe/lib/theme-presets";

export const UI_APPEARANCE_CONTROLS: ControlConfig = {
  baseColor: {
    default: "neutral",
    label: "Base color",
    options: [...BASE_COLOR_NAMES],
    type: "select",
  },
  iconLibrary: {
    default: "lucide",
    label: "Icon library",
    options: [...ICON_LIBRARIES],
    type: "select",
  },
  mode: {
    default: "system",
    label: "Color mode",
    options: ["system", "light", "dark"],
    type: "select",
  },
  themeName: {
    default: "base",
    label: "Theme",
    options: ["base", ...THEME_NAMES],
    type: "select",
  },
};

export const UI_COMPONENT_NAMES: Record<string, true> = {
  accordion: true,
  "ai-prompt-flow": true,
  "alert-dialog": true,
  "blur-in": true,
  button: true,
  caret: true,
  "chat-flow": true,
  checkbox: true,
  "checkout-flow": true,
  combobox: true,
  "command-menu": true,
  "command-menu-item": true,
  "context-menu": true,
  cursor: true,
  dialog: true,
  drawer: true,
  "dropdown-menu": true,
  "dropdown-menu-item": true,
  field: true,
  "imessage-chat-flow": true,
  input: true,
  "message-bubble": true,
  "onboarding-stepper-flow": true,
  popover: true,
  progress: true,
  radio: true,
  resizable: true,
  select: true,
  "select-item": true,
  "settings-toggle-flow": true,
  sheet: true,
  "signup-flow": true,
  skeleton: true,
  "skeleton-block": true,
  slider: true,
  spinner: true,
  stepper: true,
  switch: true,
  tabs: true,
  "telegram-chat-flow": true,
  toast: true,
  "toggle-group": true,
  tooltip: true,
  "typing-indicator": true,
};
